Content-Type: multipart/mixed; boundary="--CALLDATA--//--CALLDATA--"
MIME-Version: 1.0
Program: inkscape
Arguments: --export-dpi=1 --export-filename=Slide3.png --export-type=png Slide3.svg

----CALLDATA--//--CALLDATA--
Content-Type: application/octet-stream; Name="Slide3.png"
MIME-Version: 1.0
Content-Transfer-Encoding: base64
Content-Disposition: attachment
Filename: Slide3.png

iVBORw0KGgoAAAANSUhEUgAAAAoAAAAKCAYAAACNMs+9AAAACXBIWXMAAAAnAAAAJwEqCZFPAAAA
GXRFWHRTb2Z0d2FyZQB3d3cuaW5rc2NhcGUub3Jnm+48GgAAADFJREFUGJVjYBgwwIhL4j8DgywD
A4McVNFRFjyGKDEwMDhC2XgVPmFgYDhOqhMHEgAAHzAE3cTGGWYAAAAASUVORK5CYII=

----CALLDATA--//--CALLDATA----
