Content-Type: multipart/mixed; boundary="--CALLDATA--//--CALLDATA--"
MIME-Version: 1.0
Program: inkscape
Arguments: --export-area=0:951:47:1000 --export-filename=f6oo.png compare_file.svg

----CALLDATA--//--CALLDATA--
Content-Type: text/plain; charset="utf-8"
MIME-Version: 1.0
Content-Transfer-Encoding: base64
Filename: img

TWlzc2luZyBGaWxl

----CALLDATA--//--CALLDATA--
Content-Type: application/octet-stream; Name="f6oo.png"
MIME-Version: 1.0
Content-Transfer-Encoding: base64
Content-Disposition: attachment
Filename: f6oo.png

iVBORw0KGgoAAAANSUhEUgAAAC8AAAAxCAYAAABK+/BHAAAACXBIWXMAAA7DAAAOwwHHb6hkAAAA
GXRFWHRTb2Z0d2FyZQB3d3cuaW5rc2NhcGUub3Jnm+48GgAAAB9JREFUaIHtwQEBAAAAgiD/r25I
QAEAAAAAAAAAABcGJC0AAXI8dYQAAAAASUVORK5CYII=

----CALLDATA--//--CALLDATA----
