Content-Type: multipart/mixed; boundary="--CALLDATA--//--CALLDATA--"
MIME-Version: 1.0
Program: inkscape
Arguments: --export-area=47:0:953:49 --export-filename=guides_1.png compare_file.svg

----CALLDATA--//--CALLDATA--
Content-Type: text/plain; charset="utf-8"
MIME-Version: 1.0
Content-Transfer-Encoding: base64
Filename: img

TWlzc2luZyBGaWxl

----CALLDATA--//--CALLDATA--
Content-Type: application/octet-stream; Name="guides_1.png"
MIME-Version: 1.0
Content-Transfer-Encoding: base64
Content-Disposition: attachment
Filename: guides_1.png

iVBORw0KGgoAAAANSUhEUgAAA4oAAAAxCAYAAACcaFfTAAAACXBIWXMAAA7DAAAOwwHHb6hkAAAA
GXRFWHRTb2Z0d2FyZQB3d3cuaW5rc2NhcGUub3Jnm+48GgAAAMNJREFUeJztwTEBAAAAwqD1T20M
H6AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAATga19wABjrwhtgAAAABJRU5ErkJggg==

----CALLDATA--//--CALLDATA----
