Content-Type: multipart/mixed; boundary="--CALLDATA--//--CALLDATA--"
MIME-Version: 1.0
Program: inkscape
Arguments: --export-dpi=1 --export-filename=Slide2.png --export-type=png Slide2.svg

----CALLDATA--//--CALLDATA--
Content-Type: application/octet-stream; Name="Slide2.png"
MIME-Version: 1.0
Content-Transfer-Encoding: base64
Content-Disposition: attachment
Filename: Slide2.png

iVBORw0KGgoAAAANSUhEUgAAAAoAAAAKCAYAAACNMs+9AAAACXBIWXMAAAAnAAAAJwEqCZFPAAAA
GXRFWHRTb2Z0d2FyZQB3d3cuaW5rc2NhcGUub3Jnm+48GgAAAJ9JREFUGJXN0C9uAnEQxfHPDxYW
QVqDRfFHEE5AQoLA7BF6ARwnwKynqgYFCRaD4hakSQ0cgJ5gL7AIFkIIeJ6Zl5mX72SG91BOlBOB
H7FU9TorXUq6yy8+QTKZqCwGfr/6tvegCGWEPZUbcSqWqj0Gl+iiVWxpF76DcEuOvjUQRhv1ohU8
KMD6z/w/c2x+6J0yh9nQ6um1V9J44/PVR85E2xqRgxB1CAAAAABJRU5ErkJggg==

----CALLDATA--//--CALLDATA----
