Content-Type: multipart/mixed; boundary="--CALLDATA--//--CALLDATA--"
MIME-Version: 1.0
Program: inkscape
Arguments: --export-dpi=1 --export-filename=Slide1.png --export-type=png Slide1.svg

----CALLDATA--//--CALLDATA--
Content-Type: application/octet-stream; Name="Slide1.png"
MIME-Version: 1.0
Content-Transfer-Encoding: base64
Content-Disposition: attachment
Filename: Slide1.png

iVBORw0KGgoAAAANSUhEUgAAAAoAAAAKCAYAAACNMs+9AAAACXBIWXMAAAAnAAAAJwEqCZFPAAAA
GXRFWHRTb2Z0d2FyZQB3d3cuaW5rc2NhcGUub3Jnm+48GgAAAGFJREFUGJXlyrEJg1AYhdHzLIKg
VRBS2DuDpaO93nFSSkYxC7hBEvgtfIXOkAOX23zJ4VY+yuDnpCr/Cb5v7i8eE2StWeMqR9AFYzA+
B/2y2pbVJqsvaZBK3AXJrJG1/toOYHQZ6KZhWDQAAAAASUVORK5CYII=

----CALLDATA--//--CALLDATA----
