Content-Type: multipart/mixed; boundary="--CALLDATA--//--CALLDATA--"
MIME-Version: 1.0
Program: inkscape
Arguments: --export-area=953:49:1000:951 --export-filename=guides_5.png compare_file.svg

----CALLDATA--//--CALLDATA--
Content-Type: text/plain; charset="utf-8"
MIME-Version: 1.0
Content-Transfer-Encoding: base64
Filename: img

TWlzc2luZyBGaWxl

----CALLDATA--//--CALLDATA--
Content-Type: application/octet-stream; Name="guides_5.png"
MIME-Version: 1.0
Content-Transfer-Encoding: base64
Content-Disposition: attachment
Filename: guides_5.png

iVBORw0KGgoAAAANSUhEUgAAAC8AAAOGCAYAAAB83MkXAAAACXBIWXMAAA7DAAAOwwHHb6hkAAAA
GXRFWHRTb2Z0d2FyZQB3d3cuaW5rc2NhcGUub3Jnm+48GgAAALxJREFUeJztwQENAAAAwqD3T20P
BxQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMCDAZoM
AAG1xnPlAAAAAElFTkSuQmCC

----CALLDATA--//--CALLDATA----
